repos:
  # Autoformat: Python
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # Autoformat: js, markdown, yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
