name: Discussion
description: Start a discussion with the community.
title: "[Discussion]: "
labels: ["discussion point"]
assignees: ["sa-tre/spec-maintainers"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being involved in the SATRE community.

        This issue form is for starting a discussion about the specification with the community.

        For example, you may want to start a conversation about a particular aspect of the specification, or try to find consensus prior to submitting a proposal for change.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Please write a brief summary of the point you would like to discuss.
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Source
      description: (Optional) Please share the source of this issue - e.g. personal contribution, SATRE survey, Collaboration Cafe discussion...
  - type: textarea
    id: detail
    attributes:
      label: Detail
      description: Please explain the point you would like to discuss. Feel free to include references that may be useful.
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Intended Output
      description: What do you hope will happen as a result of this discussion?
    validations:
      required: false
  - type: textarea
    id: tags
    attributes:
      label: Who can help
      description: Tag anyone who you think will be interested or who can help by typing `@` followed by their GitHub username.
    validations:
      required: false
